"""
The Librarian — System 4: Unprompted Observation Engine

Generates contextual observations from session summaries and recent entries,
detecting cross-session patterns, stale threads, absence, contradictions, and progress.

Pure functions — no Librarian dependencies. Suitable for standalone integration
into host applications that manage sessions and entries.

Usage:
    from solitaire.core.observer import (
        generate_observations,
        check_suppression,
        format_observation,
        Observation,
        ObservationType,
    )

    observations = generate_observations(
        session_summaries=[{"session_id": "...", "summary": "...", "ended_at": "..."}],
        recent_entries=[{"id": "...", "content": "...", "category": "...", "tags": "...", "created_at": "..."}],
        current_message="..."
    )

    # Filter by suppression
    for obs in observations:
        if not check_suppression(obs.topic, suppressions):
            print(format_observation(obs))
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional, Dict, Any
from collections import Counter
from datetime import datetime, timedelta
import re


# ─── Observation Types ────────────────────────────────────────────────────────

class ObservationType(str, Enum):
    """Enumeration of possible observation types."""
    PATTERN = "cross_session_pattern"
    CONTRADICTION = "contradiction_alert"
    STALE_THREAD = "stale_thread"
    PROGRESS = "progress_tracking"
    ABSENCE = "absence_detection"


# ─── Core Data Structures ─────────────────────────────────────────────────────

@dataclass
class Observation:
    """
    A single observation generated by the observer engine.

    Represents a noteworthy pattern, anomaly, or contextual insight
    that should be surfaced to the Chief Librarian.
    """
    type: ObservationType
    summary: str                          # Human-readable observation
    supporting_entry_ids: List[str] = field(default_factory=list)
    topic: str = ""                       # What this is about
    suggested_framing: str = ""           # How the Chief should say it
    significance: float = 0.5             # 0.0-1.0 confidence/importance
    suppressible: bool = True             # Can user dismiss this


# ─── Suppression Tracking ─────────────────────────────────────────────────────

@dataclass
class Suppression:
    """Tracks a suppressed topic and when it expires."""
    topic: str
    suppressed_at: str
    expires_sessions: int
    sessions_remaining: int


# ─── Static Configuration ─────────────────────────────────────────────────────

STOPWORDS = {
    "the", "a", "an", "and", "or", "but", "not", "is", "are", "am", "be", "been",
    "being", "have", "has", "had", "having", "do", "does", "did", "doing", "can",
    "could", "may", "might", "must", "shall", "should", "will", "would", "want",
    "to", "of", "in", "on", "at", "by", "for", "from", "with", "about", "as",
    "into", "through", "during", "before", "after", "above", "below", "between",
    "under", "again", "further", "then", "once", "where", "when", "why", "how",
    "all", "both", "each", "few", "more", "most", "other", "some", "such", "no",
    "nor", "only", "own", "so", "than", "too", "very", "s", "t", "can", "just",
    "don", "now", "that", "which", "who", "what", "this", "these", "those",
    "i", "you", "he", "she", "it", "we", "they", "me", "him", "her", "us", "them",
}

SENSITIVE_KEYWORDS = {
    "secret", "private", "personal", "emotional", "mental", "health", "medical",
    "financial", "password", "credential", "token", "key", "security", "abuse",
    "trauma", "depression", "anxiety", "grief", "intimate", "confidential",
}

PROGRESS_MARKERS = {
    "completed", "finished", "done", "achieved", "succeeded", "built", "fixed",
    "solved", "resolved", "delivered", "launched", "published", "implemented",
    "deployed", "released", "shipped", "passed", "won", "breakthrough",
}

STALE_INDICATORS = {
    "todo", "need to", "should", "plan to", "going to", "want to", "will",
    "upcoming", "later", "next", "soon", "eventually", "eventually", "someday",
    "pending", "outstanding", "incomplete", "unfinished", "work in progress", "wip",
}


# ─── Token Utilities ──────────────────────────────────────────────────────────

def _tokenize(text: str) -> List[str]:
    """
    Simple word tokenizer with lowercasing.
    Splits on whitespace and punctuation, filters empty tokens.
    """
    # Convert to lowercase and split on non-alphanumeric (except hyphens, underscores)
    tokens = re.findall(r'[a-z0-9_-]+', text.lower())
    return [t for t in tokens if t and len(t) > 1]


def _extract_keywords(text: str, min_length: int = 3) -> List[str]:
    """
    Extract content keywords from text, filtering stopwords.
    """
    tokens = _tokenize(text)
    keywords = [
        t for t in tokens
        if t not in STOPWORDS and len(t) >= min_length
    ]
    return keywords


def _is_sensitive_topic(keywords: List[str]) -> bool:
    """
    Check if a set of keywords relates to sensitive personal content.
    Returns True if any sensitive keyword is detected.
    """
    keyword_set = set(keywords)
    return bool(keyword_set & SENSITIVE_KEYWORDS)


# ─── Date Parsing ────────────────────────────────────────────────────────────

def _parse_iso_datetime(dt_str: Optional[str]) -> Optional[datetime]:
    """
    Parse ISO 8601 datetime string to datetime object.
    Returns None if parsing fails or input is None.
    """
    if not dt_str:
        return None
    try:
        # Try ISO format with timezone
        return datetime.fromisoformat(dt_str.replace('Z', '+00:00'))
    except (ValueError, AttributeError):
        try:
            # Try basic ISO format without timezone
            return datetime.fromisoformat(dt_str)
        except (ValueError, AttributeError):
            return None


def _days_ago(dt: Optional[datetime], now: Optional[datetime] = None) -> Optional[int]:
    """
    Calculate number of days elapsed since dt to now.
    Returns None if dt is None.
    """
    if not dt:
        return None
    if now is None:
        now = datetime.utcnow()
    delta = now - dt
    return delta.days


# ─── Observation Detection ───────────────────────────────────────────────────

def _detect_cross_session_patterns(
    session_summaries: List[Dict[str, Any]],
    recent_entries: List[Dict[str, Any]],
    current_message: str,
) -> Optional[Observation]:
    """
    Detect topics/keywords that appear in 3+ of last 5 session summaries.
    If topic appears frequently but current message doesn't reference it,
    generate an observation.

    Returns: Observation or None if no pattern found.
    """
    if len(session_summaries) < 3:
        return None

    # Extract keywords from recent summaries (last 5)
    recent_sums = session_summaries[-5:]
    all_keywords = []
    summary_keywords_list = []

    for summary_dict in recent_sums:
        summary_text = summary_dict.get("summary", "")
        keywords = _extract_keywords(summary_text)
        summary_keywords_list.append(keywords)
        all_keywords.extend(keywords)

    # Count keyword frequency across summaries
    keyword_frequency = Counter(all_keywords)

    # Find keywords appearing in 3+ of the last 5 summaries
    keywords_in_3plus = []
    for keyword, count in keyword_frequency.most_common():
        # Count how many summaries contain this keyword
        summary_count = sum(1 for kw_list in summary_keywords_list if keyword in kw_list)
        if summary_count >= 3:
            keywords_in_3plus.append((keyword, summary_count))

    if not keywords_in_3plus:
        return None

    # Check if current message references the top recurring keyword
    top_keyword, frequency = keywords_in_3plus[0]
    current_keywords = _extract_keywords(current_message)

    if top_keyword in current_keywords:
        # Current message already addresses it
        return None

    # Construct observation
    supporting_ids = []
    for entry in recent_entries:
        entry_keywords = _extract_keywords(entry.get("content", ""))
        if top_keyword in entry_keywords:
            supporting_ids.append(entry.get("id", ""))

    significance = min(1.0, frequency / 5.0)  # Normalize to 5 sessions

    return Observation(
        type=ObservationType.PATTERN,
        summary=f"Topic '{top_keyword}' has appeared in {frequency} of your last 5 sessions, but isn't mentioned yet.",
        supporting_entry_ids=supporting_ids[:3],  # Top 3
        topic=top_keyword,
        suggested_framing=f"I notice you've been working on {top_keyword} across several recent sessions. Should we revisit that context?",
        significance=significance,
        suppressible=True,
    )


def _detect_stale_threads(
    recent_entries: List[Dict[str, Any]],
    now: Optional[datetime] = None,
) -> Optional[Observation]:
    """
    Find entries with category 'user_knowledge' or 'implementation' containing
    stale indicators (TODO, "need to", etc) that are older than 3 days
    and haven't been referenced recently. Max 1 observation.

    Returns: Observation or None if no stale thread found.
    """
    if now is None:
        now = datetime.utcnow()

    stale_candidates = []

    for entry in recent_entries:
        category = entry.get("category", "").lower()
        if category not in ("user_knowledge", "implementation"):
            continue

        content = entry.get("content", "").lower()
        created_at_str = entry.get("created_at")
        created_at = _parse_iso_datetime(created_at_str)

        # Check if entry is older than 3 days
        days_old = _days_ago(created_at, now)
        if days_old is None or days_old < 3:
            continue

        # Check for stale indicators
        has_stale_indicator = any(
            indicator in content
            for indicator in STALE_INDICATORS
        )

        if has_stale_indicator:
            stale_candidates.append({
                "entry": entry,
                "days_old": days_old,
                "content": content,
            })

    if not stale_candidates:
        return None

    # Pick the oldest one (highest impact)
    stale_candidates.sort(key=lambda x: x["days_old"], reverse=True)
    stale = stale_candidates[0]

    entry_id = stale["entry"].get("id", "")
    days_old = stale["days_old"]

    # Extract the incomplete item (first sentence with stale indicator)
    content_text = stale["entry"].get("content", "")
    sentences = re.split(r'[.!?]', content_text)
    incomplete_task = "this task"
    for sentence in sentences:
        if any(ind in sentence.lower() for ind in STALE_INDICATORS):
            incomplete_task = sentence.strip()[:80]  # First 80 chars
            break

    return Observation(
        type=ObservationType.STALE_THREAD,
        summary=f"You have an incomplete item from {days_old} days ago: '{incomplete_task}...'",
        supporting_entry_ids=[entry_id],
        topic=incomplete_task,
        suggested_framing=f"I found something from {days_old} days ago that still needs attention: '{incomplete_task}'. Should we revisit it?",
        significance=min(1.0, days_old / 30.0),  # Normalize: 30 days = max significance
        suppressible=True,
    )


def _detect_absence(
    recent_entries: List[Dict[str, Any]],
    now: Optional[datetime] = None,
) -> Optional[Observation]:
    """
    Check for topics/proper nouns that appeared frequently in entries older
    than 7 days but not in the last 7 days. Simple keyword frequency comparison.

    Returns: Observation or None if no absence detected.
    """
    if now is None:
        now = datetime.utcnow()

    cutoff_old = now - timedelta(days=14)
    cutoff_recent = now - timedelta(days=7)

    old_entries = []
    recent_entries_list = []

    for entry in recent_entries:
        created_at_str = entry.get("created_at")
        created_at = _parse_iso_datetime(created_at_str)

        if created_at is None:
            continue

        if created_at < cutoff_old:
            old_entries.append(entry)
        elif created_at >= cutoff_recent:
            recent_entries_list.append(entry)

    if not old_entries or not recent_entries_list:
        return None

    # Extract keywords from old entries
    old_keywords = []
    for entry in old_entries:
        keywords = _extract_keywords(entry.get("content", ""))
        old_keywords.extend(keywords)

    old_keyword_counts = Counter(old_keywords)

    # Extract keywords from recent entries
    recent_keywords = []
    for entry in recent_entries_list:
        keywords = _extract_keywords(entry.get("content", ""))
        recent_keywords.extend(keywords)

    recent_keyword_set = set(recent_keywords)

    # Find keywords that were frequent in old entries but absent in recent
    disappeared_keywords = []
    for keyword, old_count in old_keyword_counts.most_common(10):
        if old_count >= 2 and keyword not in recent_keyword_set:
            disappeared_keywords.append((keyword, old_count))

    if not disappeared_keywords:
        return None

    top_keyword, old_count = disappeared_keywords[0]

    # Find old entries that mention this keyword
    supporting_ids = []
    for entry in old_entries:
        if top_keyword in _extract_keywords(entry.get("content", "")):
            supporting_ids.append(entry.get("id", ""))

    return Observation(
        type=ObservationType.ABSENCE,
        summary=f"'{top_keyword}' was a frequent topic over the past weeks, but hasn't appeared recently.",
        supporting_entry_ids=supporting_ids[:3],
        topic=top_keyword,
        suggested_framing=f"I notice '{top_keyword}' was on your radar before, but I haven't seen it mentioned in the last week. Is that intentional, or should we follow up?",
        significance=min(1.0, old_count / 5.0),  # Normalize to 5 mentions
        suppressible=True,
    )


# ─── Public API ───────────────────────────────────────────────────────────────

def generate_observations(
    session_summaries: List[Dict[str, Any]],
    recent_entries: List[Dict[str, Any]],
    current_message: str = "",
) -> List[Observation]:
    """
    Generate observations from session summaries and recent entries.

    Input format for session_summaries:
        [{"session_id": "...", "summary": "...", "ended_at": "..."}]

    Input format for recent_entries:
        [{"id": "...", "content": "...", "category": "...", "tags": "...", "created_at": "..."}]

    Detection logic:
        - Cross-session patterns: topics appearing in 3+ of last 5 sessions
        - Stale threads: incomplete items (TODO, "need to") older than 3 days
        - Absence detection: topics frequent 7+ days ago but absent recently

    Guardrails:
        - Max 2 observations returned per call
        - Sorted by significance (highest first)
        - Filters sensitive topics
        - Only returns observations with significance > 0.5

    Args:
        session_summaries: List of session summary dicts
        recent_entries: List of entry dicts
        current_message: Optional current user message (to avoid redundant patterns)

    Returns:
        List of observations, sorted by significance (max 2)
    """
    observations = []

    # Detect cross-session patterns
    pattern_obs = _detect_cross_session_patterns(
        session_summaries, recent_entries, current_message
    )
    if pattern_obs and pattern_obs.significance > 0.5:
        if not _is_sensitive_topic(_extract_keywords(pattern_obs.topic)):
            observations.append(pattern_obs)

    # Detect stale threads
    stale_obs = _detect_stale_threads(recent_entries)
    if stale_obs and stale_obs.significance > 0.5:
        if not _is_sensitive_topic(_extract_keywords(stale_obs.topic)):
            observations.append(stale_obs)

    # Detect absence
    absence_obs = _detect_absence(recent_entries)
    if absence_obs and absence_obs.significance > 0.5:
        if not _is_sensitive_topic(_extract_keywords(absence_obs.topic)):
            observations.append(absence_obs)

    # Sort by significance and return top 2
    observations.sort(key=lambda obs: obs.significance, reverse=True)
    return observations[:2]


def check_suppression(topic: str, suppressions: List[Dict[str, Any]]) -> bool:
    """
    Check if a topic is currently suppressed.

    Suppression format:
        [{"topic": "...", "suppressed_at": "...", "expires_sessions": 3, "sessions_remaining": 2}]

    Args:
        topic: The topic to check
        suppressions: List of active suppressions

    Returns:
        True if the topic is suppressed (sessions_remaining > 0), False otherwise
    """
    for suppression in suppressions:
        if suppression.get("topic") == topic:
            sessions_remaining = suppression.get("sessions_remaining", 0)
            return sessions_remaining > 0
    return False


def format_observation(obs: Observation) -> str:
    """
    Format an observation for display using its suggested framing.

    Args:
        obs: The observation to format

    Returns:
        The suggested framing text
    """
    return obs.suggested_framing
